name = "dopel-rpc"
main = "src/index.ts"
compatibility_date = "2024-06-20"

# For workers.dev deployments (default). After you add a custom domain in the dashboard,
# Cloudflare manages the route automatically.

[vars]
# Optional non‑secret defaults can go here

